site_name: Genemede
nav:
  - index.md
  - About: about.md
  - Components: components.md
  - Tutorial: tutorial.md
  - Developer Guide: 'developer/index.md'
  - Reference: 'reference/index.md'

theme:
  #name: readthedocs
  name: mkdocs
  color_mode: dark
  user_color_mode_toggle: true
  locale: en

hooks:
  - src/hooktest.py

plugins:
- search
- gen-files:
    scripts:
    - src/refgenerator.py
#- mkdocstrings

watch:
  - src
extra_css:
  - gnmd.css

markdown_extensions:
  - attr_list